language: node_js
node_js:
  - '10.17.0'
  - '9.0'
  - '8.0'
  - '7.0'
install:
  - yarn 
script:
  - npm test
before_deploy:
  - npm run build
deploy:
  provider: npm
  email: $EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
